export const mapaCidadesBase: Record<string, string> = {

  "salvador": "BA",
  "fortaleza": "CE",
  "recife": "PE",
  "são luís": "MA",
  "maceió": "AL",
  "teresina": "PI",
  "natal": "RN",
  "joão pessoa": "PB",
  "aracaju": "SE",

  "abreu e lima": "PE",
  "acu": "RN",
  "alagoinhas": "BA",

  "aracati": "CE",
  "arraial d'ajuda": "BA",
  "aruja": "SP",
  "barra da estiva": "BA",
  "barra do inga": "PB",
  "barreiras": "BA",
  "bayeux": "PB",
  "bom jesus da lapa": "BA",
  "cabo de santo agostinho": "PE",
  "caico": "RN",
  "cajazeiras": "PB",
  "camacari": "BA",
  "camaçari": "BA",
  "camela": "PE",
  "campo formoso": "BA",
  "caninde de sao francisco": "SE",
  "capao redondo": "SP",
  "caxias": "MA",
  "codo": "MA",
  "conceicao do coite": "BA",
  "conceicao do jacuipe": "BA",
  "cruz das almas": "BA",
  "curado": "PE",
  "currais novos": "RN",
  "dias d'avila": "BA",
  "eunapolis": "BA",
  "eusebio": "CE",
  "frutuós gomes": "RN",
  "gandu": "BA",
  "garanhuns": "PE",
  "ilhéus": "BA",
  "imperatriz": "MA",
  "ipu": "CE",
  "itabuna": "BA",
  "itapage": "CE",
  "itapetinga": "BA",
  "jaboatao dos guararapes": "PE",
  "jequie": "BA",
  "lagarto": "SE",
  "limeiro do norte": "CE",
  "limoeiro": "PE",
  "marechal deodoro": "AL",
  "massape": "CE",
  "moreilandia": "PE",
  "moreno": "PE",
  "mucuge": "BA",
  "muniz ferreira": "BA",
  "nova russas": "CE",
  "olinda": "PE",
  "parnamirim": "RN",
  "paulo afonso": "BA",
  "petrolina": "PE",
  "pilar": "AL",
  "pocoes": "BA",
  "posto da mata": "BA",
  "remigio": "PB",
  "riachao do dantas": "SE",
  "santa cruz cabralia": "BA",
  "santo amaro": "BA",
  "santo antonio de jesus": "BA",
  "sao raimundo nonato": "PI",
  "senhor do bonfim": "BA",
  "serrinha": "BA",
  "sitio do quinto": "BA",
  "sobrado": "PB",
  "urucui": "PI",
  "vitoria da conquista": "BA",
  "xeceu": "PE",
  "xique-xique": "BA"
};